---
title: "CityOfAnnapolis"
author: "Nicole Williamson"
date: "2023-01-19"
output: html_document
---

```{r setup, include=FALSE, message=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE, message=FALSE, warning=FALSE}
#Install/load packages
library("tidyr")
library("dplyr")
library("readr")
library("ggplot2")
```

```{r, include=FALSE, message=FALSE, warning=FALSE}
# Code for joining data sets (could use left or right join instead) 
MyMerge       <- function(x, y){
  df            <- merge(x, y, all = TRUE)
  rownames(df)  <- df$Row.names
  df$Row.names  <- NULL
  return(df)
}
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}

# read in water usage data
waterusage <- read.csv("../Data/PumpReports_CityOfAnnapolis.csv")

# get total avg usage across all permits for each year 
total_avg_usage <- waterusage %>% group_by(year) %>% summarise_at(vars(annual_avg), list(annual_avg = sum ), na.rm = TRUE)
total_avg_usage["permit"] <- c("total_annual_avg")

# Join the two datasets 
waterusage <- Reduce(MyMerge, list(waterusage, total_avg_usage))



#check for errors in naming convention 
unique(waterusage$permit)

max(total_avg_usage$annual_avg)
```

# Line Graphs

## All Permits
```{r, echo=FALSE, message=FALSE, warning=FALSE}

ggplot(data = waterusage, aes(x = year, y= annual_avg, color = permit))+
  scale_color_manual(values = c("AA1972G009" = "#e81e63",
                                "AA1972G209" = "#2196f3",
                                "AA1972G309" = "#8bc34a",
                                "total_annual_avg" = "black"))+
  geom_line(size = .75)+
  theme_light()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        axis.text.x = element_text(color = "black", size = 8, angle = 45, hjust = 1),
        axis.text.y = element_text(color = "black", size = 8),
        axis.line = element_line(colour = "black", linetype = "solid"), 
        legend.position="none",
        plot.title = element_text(hjust = .5))+
  scale_x_continuous(breaks = c(1975, 1980, 1985, 1990, 1995, 2000, 2005, 2010, 2015, 2020, 2025))+
  geom_hline(yintercept = 1650000, color = "#e81e63", linetype= "dashed")+
  geom_hline(yintercept = 2000000, color = "#2196f3", linetype= "dashed")+
  geom_hline(yintercept = 1850000, color = "#8bc34a", linetype= "dashed")+
  geom_hline(yintercept = 5500000, color = "black", linetype= "dashed")+
  annotate("text", x = 2017.5, y= 1750000, label = "Perminted annual avg - 1,650,000 gpd", color = "#e81e63", size = 2.5)+
  annotate("text", x = 2017.5, y= 2100000, label = "Perminted annual avg - 2,000,000 gpd", color = "#2196f3", size = 2.5)+
  annotate("text", x = 2017.5, y= 1950000, label = "Perminted annual avg - 1,850,000 gpd", color = "#8bc34a", size = 2.5)+
  annotate("text", x = 2000, y= 5600000, label = "Combined Total Permitted Withdrawal  - 5,500,000 gpd", color = "black", size = 2.5)+
  labs(y = "Annual Average Water Ussage (gpd)", x = "Year")+
  guides(color=guide_legend(" "))+
  theme(legend.position="bottom")

ggsave("../Figures/CityOfAnnapolis_WaterUsage.jpeg")
```